#include "Functions.h"
void main()
{
	setlocale(LC_ALL, "Russian");
	const int n = 10;
	int arr[n];
	char b_arr[n];
	double c_arr[n];
	int d_arr[ROWS][COLS];
	const int m = 8;
	const int z = 5;
	cout << "Элементы одномерного массива; (типа int, char double)";
	cout << delimiter;
	FillRand(arr, n);
	Print(arr, n);
	cout << delimiter;
	FillRand(b_arr, n);
	Print(b_arr, n);
	cout << delimiter;
	FillRand(c_arr, n);
	Print(c_arr, n);
	cout << delimiter;
	cout << "Отсортированный массив;";
	cout << delimiter;
	Sort(arr, n);
	Print(arr, n);
	cout << delimiter;
	Sort(c_arr, n);
	Print(c_arr, n);
	cout << delimiter;
	cout << "Сумма элементов массива: (типа int) " << Sum(arr, n);
	cout << delimiter;
	cout << "Сумма элементов массива: (типа double) " << Sum(c_arr, n);
	cout << delimiter;
	cout << "Средное значения элементов массива: (типа int) "; Avg(arr, n);
	cout << delimiter;
	cout << "Средное значения элементов массива: (типа double) "; Avg(c_arr, n);
	cout << delimiter;
	cout << "Минимальное значения массива: (типа int) "; minValueIn(arr, n);
	cout << delimiter;
	cout << "Минимальное значения массива: (типа double) "; minValueIn(c_arr, n);
	cout << delimiter;
	cout << "Максимальное значения массива: (типа int) "; maxValueIn(arr, n);
	cout << delimiter;
	cout << "Максимальное значения массива: (типа double) "; maxValueIn(c_arr, n);
	cout << delimiter;
	cout << "Перегрузка на двухмерный массив; (Элементы двухмерного массива) " << endl;
	FillRand(d_arr, ROWS, COLS);
	Print(d_arr, ROWS, COLS);
	cout << delimiter;
	cout << "Сумма элементов двухмерного массива: " << Sum(d_arr, ROWS, COLS);
	cout << delimiter;
	cout << "Средное значения двухмерного массива: "; Avg(d_arr);
	cout << delimiter;
	cout << "Отсортированный двухмерный массив; ";
	cout << delimiter;
	Sort(d_arr, ROWS, COLS);
	Print(d_arr, ROWS, COLS);
	cout << delimiter;
	cout << "Минимальное значения двухмерного массива: "; minValueIn(d_arr, ROWS, COLS);
	cout << delimiter;
	cout << "Максимальное значения двухмерного массива: "; maxValueIn(d_arr, ROWS, COLS);
}
